services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: default
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
